### ISSUE TITLE
Multiplayer Server crashes after player language change

### ISSUE THREAD

**Issue by Energeneer** [raiguard/Factorio-QuickItemSearch#36] opened 2024-01-01 21:22 UTC
### Description

The mod Quick Item Search (2.1.8) caused a non-recoverable error.
Please report this error to the mod author.

```
Error while running event QuickItemSearch::Custom event (ID 257)
Gui element with name qis_search_window already present in the parent element.
stack traceback:

[C]: in function 'add'
flib/gui.lua:85: in function 'recursive_build'
flib/gui.lua:150: in function 'build'
QuickItemSearch/scripts/gui/search.lua:14: in function 'build'
QuickItemSearch/control.lua:147: in function <QuickItemSearch/control.lua:128>
[C]: in function 'raise_event'
flib/dictionary-lite.lua:332: in function <flib/dictionary-lite.lua:314>
stack traceback:
[C]: in function 'raise_event'
flib/dictionary-lite.lua:332: in function <flib/dictionary-lite.lua:314>
```

### Reproduction

1. Host a Server with multiple people.
2. Have one of the players (that had already successfully joined) change their language (in our case from Automatic German to English)
3. When this person re-joins, the server crashes. The client seems fine, get's a disconnnect, though.
4. The error persists after
 - A factorio restart
 - A full reinstall of mods (Deleting and re-downloading)
 - A factorio reinstall using steam
5. After all steps described above, the server crashes after the map has loaded and the faulty player can see the character on the map.

**Comment by Energeneer** [comment] 2024-01-01 21:22
See also #35

**Comment by Energeneer** [comment] 2024-01-01 21:32
Mods installed
[mod-list.json](https://github.com/raiguard/QuickItemSearch/files/13806051/mod-list.json)


Logfile (Server)
[factorio-current.log](https://github.com/raiguard/QuickItemSearch/files/13806053/factorio-current.log)

Save File
See https://github.com/raiguard/QuickItemSearch/issues/35#issuecomment-1873483644

**Comment by Energeneer** [comment] 2024-01-01 21:34
A full new map and a complete reinstall of factorio, complete with deleting the %appdata%\Factorio folder fixed the issue. Futhermore, the language was changed before any mods were installed.

**Comment by raiguard** [comment] 2024-05-07 06:58
Duplicate of #35.

**Closed as not planned by raiguard** 2024-05-07 06:58 UTC
